FROM node:22 AS builder

WORKDIR /build

RUN npm install -g pnpm

COPY . .

RUN pnpm install --frozen-lockfile && pnpm build-all

FROM node:22 AS runtime

COPY --from=builder /build/node_modules /node_modules

WORKDIR /app/db-provisioner

COPY --from=builder /build/packages/db-provisioner/node_modules ./node_modules
COPY --from=builder /build/packages/db-provisioner/dist ./dist
COPY --from=builder /build/packages/db-provisioner/prisma ./prisma
COPY --from=builder /build/packages/db-provisioner/package.json ./package.json

CMD npx prisma migrate deploy