FROM node:22 AS builder

WORKDIR /build

RUN npm install -g pnpm

COPY . .

RUN pnpm install --frozen-lockfile && pnpm build-all

FROM node:22 AS runtime

COPY --from=builder /build/node_modules /node_modules

WORKDIR /app/url-backend

COPY --from=builder /build/apps/url-backend/node_modules ./node_modules
COPY --from=builder /build/apps/url-backend/dist ./dist

CMD node dist/main.js