FROM node:22 AS builder

WORKDIR /build

RUN npm install -g pnpm

COPY . .

RUN pnpm install --frozen-lockfile && pnpm build-all

FROM node:22 AS runtime

WORKDIR /app

COPY --from=builder /build/apps/admin-backend/node_modules ./node_modules
COPY --from=builder /build/apps/admin-backend/dist ./dist

CMD node dist/main.js